service: helloworld
provider:   
  name: aws   
  runtime: nodejs10.x
  region: ap-southeast-1	
functions:
  app:
    handler: handler.index
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'    
  
plugins:
  - serverless-offline
  - serverless-dynamodb-local
